defaults:
  - override hydra/job_logging: disabled

environment:
  seed: 42

model:
  # name: andresnowak/Qwen3-0.6B-instruction-finetuned
  name: Qwen/Qwen3-0.6B-Base
  hub_model_id: andresnowak/Qwen3-0.6B-MNLP_mcqa_model_text

dataset_train:
  - name: andresnowak/MNLP_MCQA_dataset_2
    config: train
    subset_name: math_qa
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: ScienceQA
    config: train
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: mmlu-auxiliary-train-auto-labelled
    config: train
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: ai2_arc_challenge
    config: train
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: ai2_arc_easy
    config: train
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: medmcqa
    config: train
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: openbookqa
    config: train
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: sciq
    config: train

dataset_validation:
  - name: andresnowak/MNLP_MCQA_dataset_2
    config: validation
    subset_name: math_qa
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: ScienceQA
    config: validation
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: mmlu
    config: validation
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: ai2_arc_challenge
    config: validation
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: ai2_arc_easy
    config: validation
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: medmcqa
    config: validation
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: openbookqa
    config: validation
  - name: andresnowak/MNLP_MCQA_dataset_2
    subset_name: sciq
    config: validation

dataset_mmlu:
  - name: cais/mmlu
    config: validation
    subjects: ["abstract_algebra", "anatomy", "astronomy", "college_biology", "college_chemistry", "college_computer_science", "college_mathematics", "college_physics", "computer_security", "conceptual_physics", "electrical_engineering", "elementary_mathematics", "high_school_biology",  "high_school_chemistry", "high_school_computer_science", "high_school_mathematics", "high_school_physics", "high_school_statistics", "machine_learning"]


training:
  output_dir: ./output
  logging_dir: ./logs
  resume_dir: None
  report_to: wandb
  push_to_hub: true
  learning_rate: 1e-5
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 32 # to get effective 64
  num_train_epochs: 2
  weight_decay: 0.00
  warmup_ratio: 0.1
  max_grad_norm: 0.5
  linear_layers_max_grad_norm: 1.0
  completion_only_loss: False

wandb:
  project: MNLP-qwen-instruction-finetuning
  name: qwen-instruction-finetuning-MCQA-text


# from datasets import interleave_datasets

# mixture = interleave_datasets(
#     [ds1, ds2, ds3],
#     probabilities=[1.0, 1.0, 1.0]
# )
