program: train.py
method: bayes
metric:
  name: eval/loss
  goal: minimize
parameters:
  learning_rate:
    min: 1e-6
    max: 1e-4
    distribution: log_uniform
  per_device_train_batch_size:
    values: [8]  # Multiple values to test
  num_train_epochs:
    values: [2]
  weight_decay:
    values: [0.0]
command:
  - python
  - ${program}